logo: /assets/img/logo.png

---
title: YAML Front Matter
description: A very simple way to add structured data to a page.
---
<h1> {{ title }} </h1>
<p> {{ description }} </p>

show_downloads: false
google_analytics_code: UA-131831879-1
theme: jekyll-theme-minimal
