logo: /assets/img/logo.png

title: Eden M
description: B.S. in Physics
description: University of California, Los Angeles
show_downloads: false
google_analytics: UA-131831879-1
theme: jekyll-theme-minimal
