logo: /assets/img/logo.png

title: Eden M
description: B.S. Physics from the University of California, Los Angeles
show_downloads: false
google_analytics_code: UA-131831879-1
theme: jekyll-theme-minimal
